[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''

[tool.pylint.'MESSAGES CONTROL']
disable = [
  "too-many-public-methods",
  "too-many-return-statements",
  "too-many-instance-attributes",
  "too-many-arguments",
  "logging-fstring-interpolation",
  "too-many-lines",
  "too-many-statements",
  "too-many-branches",
  "logging-not-lazy",
  "unspecified-encoding",
  "too-many-locals",
  "fixme"
]
[tool.pylint.basic]
good-names-rgxs = "^[_a-z][_a-z0-9]?$"

