name: docker build cryptobot:TAG
on:
  push:
    tags:
      - "*"
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: self-hosted
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pull latest base image
        run:
          docker pull ubuntu:focal

      - name: docker build latest
        run: |
          ./run build TAG=latest
          docker -t ghcr.io/azulinho/cryptobot:latest ghcr.io/azulinho/cryptobot:${{ github.ref_name }}

      - name: docker push latest and tag
        run: |
          docker push ghcr.io/azulinho/cryptobot:latest
          docker push ghcr.io/azulinho/cryptobot:${{ github.ref_name }}

      - name: sets python version to pyston
        run: |
          echo pyston-2.3.5 > .python-version

      - name: docker build pyston
        run:
          ./run build TAG=pyston

      - name: docker push pyston
        run:
          docker push ghcr.io/azulinho/cryptobot:pyston

      - name: sets python version to pypy
        run: |
          echo pypy3.9-7.3.11 > .python-version

      - name: docker build pypy
        run:
          ./run build TAG=pypy

      - name: docker push pypy
        run:
          docker push ghcr.io/azulinho/cryptobot:pypy
